### ISSUE TITLE
HELP?

### ISSUE THREAD

**Issue by LegitSoulja** [XtremePlayzCODE/randmath#1]
Dude do you need help?

**Comment by XtremePlayzCODE** [comment]
I did. Until you rudely speak to me on skype. Anyways, your not getting my new OgarUL that can be connected to from Agar.io without clients or mods, unless you could be nice

P.S. That github convo was getting intense

**Comment by LegitSoulja** [comment]
@XtremePlayzCODE I don't want your shit.. Your shit doesnt even work kiddo.
